; ===== 自动生成说明 =====
; 配置名称: router
; 生成时间: 2026-03-11 09:58:13
; 规则集(13):
;   🎯 全球直连、🤖 智能助手、🚀 节点选择、🕹 PT下载、🛑 全球拦截、🍃 应用净化、📢 谷歌FCM
;   Ⓜ️ 微软服务、🍎 苹果服务、📲 电报信息、🎬 影音刮削、🌍 国外媒体、🐟 漏网之鱼
; 策略组(15):
;   🚀 节点选择、♻️ 自动选择、📉️ 超低倍率、🌍 国外媒体、📲 电报信息、🎬 影音刮削、🤖 智能助手
;   Ⓜ️ 微软服务、🕹 PT下载、🍎 苹果服务、📢 谷歌FCM、🎯 全球直连、🛑 全球拦截、🍃 应用净化
;   🐟 漏网之鱼
; ========================

[custom]
ruleset=🎯 全球直连,https://raw.githubusercontent.com/Sowevo/subconverter/main/Ruleset/Direct.list
ruleset=🤖 智能助手,https://raw.githubusercontent.com/Sowevo/subconverter/main/Ruleset/AIGC.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/Sowevo/subconverter/main/Ruleset/Proxy.list
ruleset=🕹 PT下载,https://raw.githubusercontent.com/Sowevo/subconverter/main/Ruleset/PrivateTracker.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 电报信息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🎬 影音刮削,https://raw.githubusercontent.com/Sowevo/subconverter/main/Ruleset/MediaScraper.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]📉️ 超低倍率`[]DIRECT`.*
;自动选择只要主流节点,排除回家以及列出来的这些Emoji的节点...是不是反过来写比较好
custom_proxy_group=♻️ 自动选择`url-test`^(?:(?!🏠|🇦🇺|🇨🇦|🇨🇭|🇩🇪|🇪🇸|🇫🇷|🇮🇩|🇮🇪|🇮🇳|🇳🇱|🇳🇴|🇵🇭|🇷🇺|🇸🇪|🇹🇷|🇺🇦|🇻🇳|🇦🇷|🇪🇬|🇬🇧|🇰🇵|🇲🇾|🇵🇰|🇰🇷).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📉️ 超低倍率`fallback`(🧪|0\.5)`[]♻️ 自动选择`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]📉️ 超低倍率`[]🎯 全球直连`.*
custom_proxy_group=📲 电报信息`select`[]🚀 节点选择`[]♻️ 自动选择`[]📉️ 超低倍率`[]🎯 全球直连`.*
custom_proxy_group=🎬 影音刮削`load-balance`.*`http://www.gstatic.com/generate_204`300,,50
;AIGC选🇯🇵🇰🇷🇨🇳🇸🇬🇺🇸🇬🇧🇩🇪🇮🇳这些，改为自动测速
custom_proxy_group=🤖 智能助手`url-test`^(?=.*🇯🇵|🇰🇷|🇨🇳|🇸🇬|🇺🇸|🇬🇧|🇩🇪|🇮🇳).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 节点选择`[]📉️ 超低倍率`[]♻️ 自动选择`.*
custom_proxy_group=🕹 PT下载`select`[]🎯 全球直连`[]🚀 节点选择`[]📉️ 超低倍率`[]♻️ 自动选择`.*
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🚀 节点选择`[]📉️ 超低倍率`[]♻️ 自动选择`.*
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]📉️ 超低倍率`[]🎯 全球直连`[]♻️ 自动选择`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]📉️ 超低倍率`[]♻️ 自动选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]📉️ 超低倍率`[]🎯 全球直连`[]♻️ 自动选择`.*

enable_rule_generator=true
overwrite_original_rules=true
